defaults:
  - loss: cross_entropy
  - encoder: many_token_v2
  - scheduler: finetune

_target_: model.Model

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.0
  betas: [0.9, 0.95]

# compile model for faster training with pytorch 2.0
compile: False
