# @package _global_

defaults:
  - modality_encoder: siglip
  - dataset: pretrain # choose datamodule with `test_dataloader()` for evaluation
  - model: default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - _self_

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
