# @package _global_

defaults:
  - test_fixture
  - override model: debug

trainer:
  fast_dev_run: True

model:
  encoder:
    text_model_config:
      test_config:
        vocab_size: 32000
        max_position_embeddings: 128
