# @package _global_

defaults:
  - train
  - override debug: default
  - override modality_encoder: debug
  - override model: debug
  - override dataset: debug_node
  - override trainer: ddp_sim
  - _self_

trainer:
  fast_dev_run: 2
  detect_anomaly: true

model:
  scheduler:
    dataset_steps: 100
