# @package _global_

defaults:
  - test_fixture_e2e_node
  - override model/loss: contrastive_loss
  - override dataset: debug_contrastive
  - _self_

trainer:
  fast_dev_run: True
  detect_anomaly: true

model:
  loss:
    num_classes: 2
