# @package _global_

defaults:
  - train
  - override debug: default
  - override modality_encoder: debug
  - override model: debug
  - override dataset: debug_node
  - override trainer: cpu
  - _self_
