# @package _global_

defaults:
  - test_fixture
  - override model: debug
  - _self_

trainer:
  fast_dev_run: True
  detect_anomaly: true

model:
  encoder:
    text_model_config:
      test_config:
        vocab_size: 32000
        max_position_embeddings: 128
