# @package _global_

defaults:
  - test_fixture_e2e_node
  - override model/loss: contrastive_loss
  - override dataset: debug_contrastive
  - _self_

model:
  loss:
    num_classes: 2
  encoder:
    graph_stack_factory:
      graph_tfmr_factory:
        use_rope: True
