defaults:
  - model_checkpoint
  - model_summary
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/best_loss"
  mode: "min"
  save_last: True
  auto_insert_metric_name: False

model_summary:
  max_depth: 2
