defaults:
  - default

strategy:
  _target_: lightning.pytorch.strategies.FSDPStrategy
  _partial_: true
  sharding_strategy: "SHARD_GRAD_OP"

accelerator: gpu
devices: 2
use_distributed_sampler: False  # We handle this
num_nodes: 1
