_target_: datamodule.DataModule
train_batch_size: 8
test_batch_size: 32
num_workers: 8
pin_memory: True

dataset:
  _target_: "tasks.test_dataset.DummyGraphTaskDataset"
  root: "tasks/sample_test_data"
  raw_graph_path: "test10"
  output_graph_path: ${paths.data_dir}/processed_files

  train_size: 0.8
  valid_size: 0.1
  test_size: 0.1

  split_seed: 42

  image_tokenizer_key: ${modality_encoder.vision_model_name}
  text_tokenizer_key: ${modality_encoder.text_model_name}

  split_graphs: False
  strict: False
  max_distance_length: 6
  force_reload: True
  debug: True
  max_text_length: 10
