defaults:
  - default

dataset:
  _target_: "tasks.test_dataset.DummyGraphTaskDataset"
  root: "tasks/sample_test_data"
  raw_graph_path: "test10"

  split_graphs: False
  strict: False

  force_reload: True
  debug: True
  max_text_length: 10
