defaults:
  - default

dataset:
  _target_: "tasks.test_dataset.DummyNodeTaskDataset"
  root: "tasks/sample_test_data"
  raw_graph_path: "test10"
  output_graph_path: ${paths.data_dir}/processed_files

  split_graphs: True
  strict: False
  force_reload: True
  debug: True
