defaults:
  - default

dataset:
  _target_: tasks.contrastive_learning.contrastive_dataset.ContrastivePreTrainingDataset
  root: ${paths.root_dir}/tasks/contrastive_learning/giga_raw_files/
  raw_graph_path: '*/*'

  split_graphs: False
  politics_and_gender_only: False
  force_tag: "giga_pretrain"
  max_graph_size: 49

train_batch_size: 48
max_total_length: null
test_batch_size: 48
group_size: 2
