defaults:
  - default

dataset:
  _target_: tasks.contrastive_learning.contrastive_dataset.ContrastivePreTrainingDataset
  root: ${paths.root_dir}/tasks/contrastive_learning/raw_files/
  raw_graph_path: '*/*'

  split_graphs: False
