defaults:
  - default

dataset:
  _target_: tasks.contrastive_learning.contrastive_dataset.ContrastivePreTrainingDataset
  root: ${paths.root_dir}/tasks/contrastive_learning/raw_files/
  raw_graph_path: '*/*'

  split_graphs: False
  politics_and_gender_only: False
  force_tag: "pretrain"

train_batch_size: 108
max_total_length: 1080
test_batch_size: 108
