# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - default

callbacks:
  model_checkpoint: null

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    # define hyperparameter search space
    params:
      model.encoder.graph_stack_factory.num_layers: 3
      model.encoder.graph_stack_factory.graph_tfmr_factory.use_rope: choice(True, False) # choose between True, False
      model.encoder.graph_stack_factory.graph_tfmr_factory.differential_attention: choice(True, False) # choose between True, False
      seed: range(5)
