# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - default

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    # define hyperparameter search space
    params:
      model.encoder.graph_stack_factory.num_layers: 4 # choose between 3, 4
      model.encoder.graph_stack_factory.graph_tfmr_factory.use_rope: choice(False, True) # choose between True, False
      model.encoder.graph_stack_factory.graph_tfmr_factory.differential_attention: choice(False, True)  # choose between True, False
      dataset.group_size: 4 # choose between 2, 4 positives in a graph
