defaults:
  - default
  - override launcher: submitit_slurm
  - _self_

# https://hydra.cc/docs/plugins/submitit_launcher/

mode: MULTIRUN

launcher:
  submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  timeout_min: 270
  tasks_per_node: 2
  nodes: 1
  name: ${hydra.job.name}
  _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
  partition: RCOHEN
  cpus_per_task: 4
  gres: gpu:rcohengpu:2
  mem_gb: 32
  account: rcohen_group
  signal_delay_s: 120
  max_num_timeout: 0
  additional_parameters: {
    "mail-user": "l2hebert@uwaterloo.ca",
    "mail-type": "ALL",
    "signal": "SIGUSR1@90"
  }
  array_parallelism: 256
