defaults:
  - default
  - override launcher: submitit_slurm
  - _self_

# https://hydra.cc/docs/plugins/submitit_launcher/

mode: MULTIRUN

launcher:
  submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  timeout_min: 60
  tasks_per_node: 1
  mem_gb: null
  nodes: 1
  name: ${hydra.job.name}
  _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
  partition: RCOHEN
  gres: gpu:rcohengpu:1
  cpus_per_gpu: 6
  gpus_per_task: 1
  mem_per_gpu: 32GB
  account: rcohen_group
  signal_delay_s: 120
  max_num_timeout: 0
  additional_parameters: {}
  array_parallelism: 256
